data:
    mapping:
        ovor:
            " ": "00"
            "0": "01"
            "1": "02"
            "2": "03"
            "3": "04"
            "4": "05"
            "5": "06"
            "6": "07"
            "7": "08"
            "8": "09"
            "9": "0A"
            "a": "0B"
            "b": "0C"
            "c": "0D"
            "d": "0E"
            "e": "0F"
            "f": "0G"
            "g": "0H"
            "h": "0I"
            "i": "0J"
            "j": "0K"
            "k": "0L"
            "l": "0M"
            "m": "0N"
            "n": "0O"
            "o": "0P"
            "p": "0Q"
            "q": "0R"
            "r": "0S"
            "s": "0T"
            "t": "0U"
            "u": "0V"
            "v": "0W"
            "w": "0X"
            "x": "0Y"
            "y": "0Z"
            "z": "10"
            "A": "11"
            "B": "12"
            "C": "13"
            "D": "14"
            "E": "15"
            "F": "16"
            "G": "17"
            "H": "18"
            "I": "19"
            "J": "1A"
            "K": "1B"
            "L": "1C"
            "M": "1D"
            "N": "1E"
            "O": "1F"
            "P": "1G"
            "Q": "1H"
            "R": "1I"
            "S": "1J"
            "T": "1K"
            "U": "1L"
            "V": "1M"
            "W": "1N"
            "X": "1O"
            "Y": "1P"
            "Z": "1Q"
            "!": "1R"
            "@": "1S"
            "#": "1T"
            "$": "1U"
            "%": "1V"
            "^": "1W"
            "&": "1X"
            "*": "1Y"
            "(": "1Z"
            ")": "20"
            "-": "21"
            "_": "22"
            "=": "23"
            "+": "24"
            "[": "25"
            "]": "26"
            "{": "27"
            "}": "28"
            "|": "29"
            ";": "2A"
            "'": "2B"
            "\"": "2C"
            "<": "2D"
            ">": "2E"
            ",": "2F"
            ".": "30"
            "?": "31"
            "/": "32"
            "Ã¢": "33"
            "Ãª": "34"
            "Ã®": "35"
            "Ã´": "36"
            "Ã»": "37"
            "Ã‚": "38"
            "ÃŠ": "39"
            "Ã": "3A"
            "Ã”": "3B"
            "Ã›": "3C"
            "Ã¤": "3D"
            "Ã«": "3E"
            "Ã¯": "3F"
            "Ã¶": "40"
            "Ã¼": "41"
            "Ã„": "42"
            "Ã‹": "43"
            "Ã": "44"
            "Ã–": "45"
            "Ãœ": "46"
            "Ã©": "47"
            "Ã¨": "48"
            "Ã ": "49"
            "Ã‰": "4A"
            "Ãˆ": "4B"
            "Ã€": "4C"
            "Ã‡": "4D"
            "Ã™": "4E"
        sono:
            " ": "salarab"
            "0": "ğŸ‡ï¸"
            "1": "ğŸˆï¸"
            "2": "ğŸ‰ï¸"
            "3": "ğŸŠï¸"
            "4": "ğŸ‹ï¸"
            "5": "ğŸŒï¸"
            "6": "ğŸï¸"
            "7": "ğŸ¥­ï¸"
            "8": "ğŸï¸"
            "9": "ğŸï¸"
            "a": "ğŸï¸"
            "b": "ğŸ‘ï¸"
            "c": "ğŸ’ï¸"
            "d": "ğŸ“ï¸"
            "e": "ğŸ¥ï¸"
            "f": "ğŸ…ï¸"
            "g": "ğŸ¥¥ï¸"
            "h": "ğŸ¥‘ï¸"
            "i": "ğŸ†ï¸"
            "j": "ğŸ¥”ï¸"
            "k": "ğŸ¥•ï¸"
            "l": "ğŸŒ½ï¸"
            "m": "ğŸŒ¶ï¸"
            "n": "ğŸ¥’ï¸"
            "o": "ğŸ¥¬ï¸"
            "p": "ğŸ¥¦ï¸"
            "q": "ğŸ§„ï¸"
            "r": "ğŸ§…ï¸"
            "s": "ğŸ„ï¸"
            "t": "ğŸ¥œï¸"
            "u": "ğŸŒ°ï¸"
            "v": "ğŸï¸"
            "w": "ğŸ¥ï¸"
            "x": "ğŸ¥–ï¸"
            "y": "ğŸ¥¨ï¸"
            "z": "ğŸ¥¯ï¸"
            "A": "ğŸ¥ï¸"
            "B": "ğŸ§‡ï¸"
            "C": "ğŸ§€ï¸"
            "D": "ğŸ–ï¸"
            "E": "ğŸ—ï¸"
            "F": "ğŸ¥©ï¸"
            "G": "ğŸ¥“ï¸"
            "H": "ğŸ”ï¸"
            "I": "ğŸŸï¸"
            "J": "ğŸ•ï¸"
            "K": "ğŸŒ­ï¸"
            "L": "ğŸ¥ªï¸"
            "M": "ğŸŒ®ï¸"
            "N": "ğŸŒ¯ï¸"
            "O": "ğŸ¥™ï¸"
            "P": "ğŸ§†ï¸"
            "Q": "ğŸ¥šï¸"
            "R": "ğŸ³ï¸"
            "S": "ğŸ¥˜ï¸"
            "T": "ğŸ²ï¸"
            "U": "ğŸ¥£ï¸"
            "V": "ğŸ¥—ï¸"
            "W": "ğŸ¿ï¸"
            "X": "ğŸ§ˆï¸"
            "Y": "ğŸ§‚ï¸"
            "Z": "ğŸ¥«ï¸"
            "!": "ğŸ¢ï¸"
            "@": "ğŸ£ï¸"
            "#": "ğŸ¤ï¸"
            "$": "ğŸ¥ï¸"
            "%": "ğŸ¦ï¸"
            "^": "ğŸ¨ï¸"
            "&": "ğŸ©ï¸"
            "*": "ğŸªï¸"
            "(": "ğŸ«ï¸"
            ")": "ğŸ¬ï¸"
            "-": "ğŸ­ï¸"
            "_": "ğŸ¯ï¸"
            "=": "ğŸ°ï¸"
            "+": "ğŸ’’ï¸"
            "[": "ğŸ—¼ï¸"
            "]": "ğŸ—½ï¸"
            "{": "â›ªï¸"
            "}": "ğŸ•Œï¸"
            "|": "ğŸ›•ï¸"
            ";": "ğŸ•ï¸"
            "'": "â›©ï¸"
            "\"": "ğŸ•‹ï¸"
            "<": "â›²ï¸"
            ">": "â›ºï¸"
            ",": "ğŸŒï¸"
            ".": "ğŸŒƒï¸"
            "?": "ğŸ™ï¸"
            "/": "ğŸŒ„ï¸"
            "Ã¢": "âš ï¸"
            "Ãª": "ğŸš¸ï¸"
            "Ã®": "â›”ï¸"
            "Ã´": "ğŸš«ï¸"
            "Ã»": "ğŸš³ï¸"
            "Ã‚": "ğŸš­ï¸"
            "ÃŠ": "ğŸš¯ï¸"
            "Ã": "ğŸš±ï¸"
            "Ã”": "ğŸš·ï¸"
            "Ã›": "ğŸ“µï¸"
            "Ã¤": "ğŸ”ï¸"
            "Ã«": "â˜¢ï¸"
            "Ã¯": "â˜£ï¸"
            "Ã¶": "â™»ï¸"
            "Ã¼": "ğŸ“›ï¸"
            "Ã„": "ğŸ”°ï¸"
            "Ã‹": "âœ”ï¸"
            "Ã": "âŒï¸"
            "Ã–": "âšœï¸"
            "Ãœ": "â™¾ï¸"
            "Ã©": "ğŸ•ï¸"
            "Ã¨": "ğŸ”¯ï¸"
            "Ã ": "ğŸ§ï¸"
            "Ã‰": "â™¿ï¸"
            "Ãˆ": "ğŸ—¿ï¸"
            "Ã€": "âš°ï¸"
            "Ã‡": "ğŸ³ï¸â€ğŸŒˆï¸"
            "Ã™": "ğŸš½ï¸"
    chat:
        default:
            permissionNeeded: true
            permission: chat.default
        crypted:
            permissionNeeded: true
            permission: chat.crypted
        op:
            permissionNeeded: true
            permission: op
        owner:
            permissionNeeded: true
            permission: server.owner