data:
    mapping:
        sono:
            " ": "salarab"
            "0": "ğŸ‡ï¸"
            "1": "ğŸˆï¸"
            "2": "ğŸ‰ï¸"
            "3": "ğŸŠï¸"
            "4": "ğŸ‹ï¸"
            "5": "ğŸŒï¸"
            "6": "ğŸï¸"
            "7": "ğŸ¥­ï¸"
            "8": "ğŸï¸"
            "9": "ğŸï¸"
            "a": "ğŸï¸"
            "b": "ğŸ‘ï¸"
            "c": "ğŸ’ï¸"
            "d": "ğŸ“ï¸"
            "e": "ğŸ¥ï¸"
            "f": "ğŸ…ï¸"
            "g": "ğŸ¥¥ï¸"
            "h": "ğŸ¥‘ï¸"
            "i": "ğŸ†ï¸"
            "j": "ğŸ¥”ï¸"
            "k": "ğŸ¥•ï¸"
            "l": "ğŸŒ½ï¸"
            "m": "ğŸŒ¶ï¸"
            "n": "ğŸ¥’ï¸"
            "o": "ğŸ¥¬ï¸"
            "p": "ğŸ¥¦ï¸"
            "q": "ğŸ§„ï¸"
            "r": "ğŸ§…ï¸"
            "s": "ğŸ„ï¸"
            "t": "ğŸ¥œï¸"
            "u": "ğŸŒ°ï¸"
            "v": "ğŸï¸"
            "w": "ğŸ¥ï¸"
            "x": "ğŸ¥–ï¸"
            "y": "ğŸ¥¨ï¸"
            "z": "ğŸ¥¯ï¸"
            "A": "ğŸ¥ï¸"
            "B": "ğŸ§‡ï¸"
            "C": "ğŸ§€ï¸"
            "D": "ğŸ–ï¸"
            "E": "ğŸ—ï¸"
            "F": "ğŸ¥©ï¸"
            "G": "ğŸ¥“ï¸"
            "H": "ğŸ”ï¸"
            "I": "ğŸŸï¸"
            "J": "ğŸ•ï¸"
            "K": "ğŸŒ­ï¸"
            "L": "ğŸ¥ªï¸"
            "M": "ğŸŒ®ï¸"
            "N": "ğŸŒ¯ï¸"
            "O": "ğŸ¥™ï¸"
            "P": "ğŸ§†ï¸"
            "Q": "ğŸ¥šï¸"
            "R": "ğŸ³ï¸"
            "S": "ğŸ¥˜ï¸"
            "T": "ğŸ²ï¸"
            "U": "ğŸ¥£ï¸"
            "V": "ğŸ¥—ï¸"
            "W": "ğŸ¿ï¸"
            "X": "ğŸ§ˆï¸"
            "Y": "ğŸ§‚ï¸"
            "Z": "ğŸ¥«ï¸"
            "!": "ğŸ¢ï¸"
            "@": "ğŸ£ï¸"
            "#": "ğŸ¤ï¸"
            "$": "ğŸ¥ï¸"
            "%": "ğŸ¦ï¸"
            "^": "ğŸ¨ï¸"
            "&": "ğŸ©ï¸"
            "*": "ğŸªï¸"
            "(": "ğŸ«ï¸"
            ")": "ğŸ¬ï¸"
            "-": "ğŸ­ï¸"
            "_": "ğŸ¯ï¸"
            "=": "ğŸ°ï¸"
            "+": "ğŸ’’ï¸"
            "[": "ğŸ—¼ï¸"
            "]": "ğŸ—½ï¸"
            "{": "â›ªï¸"
            "}": "ğŸ•Œï¸"
            "|": "ğŸ›•ï¸"
            ";": "ğŸ•ï¸"
            "'": "â›©ï¸"
            "\"": "ğŸ•‹ï¸"
            "<": "â›²ï¸"
            ">": "â›ºï¸"
            ",": "ğŸŒï¸"
            ".": "ğŸŒƒï¸"
            "?": "ğŸ™ï¸"
            "/": "ğŸŒ„ï¸"
            "Ã¢": "âš ï¸"
            "Ãª": "ğŸš¸ï¸"
            "Ã®": "â›”ï¸"
            "Ã´": "ğŸš«ï¸"
            "Ã»": "ğŸš³ï¸"
            "Ã‚": "ğŸš­ï¸"
            "ÃŠ": "ğŸš¯ï¸"
            "Ã": "ğŸš±ï¸"
            "Ã”": "ğŸš·ï¸"
            "Ã›": "ğŸ“µï¸"
            "Ã¤": "ğŸ”ï¸"
            "Ã«": "â˜¢ï¸"
            "Ã¯": "â˜£ï¸"
            "Ã¶": "â™»ï¸"
            "Ã¼": "ğŸ“›ï¸"
            "Ã„": "ğŸ”°ï¸"
            "Ã‹": "âœ”ï¸"
            "Ã": "âŒï¸"
            "Ã–": "âšœï¸"
            "Ãœ": "â™¾ï¸"
            "Ã©": "ğŸ•ï¸"
            "Ã¨": "ğŸ”¯ï¸"
            "Ã ": "ğŸ§ï¸"
            "Ã‰": "â™¿ï¸"
            "Ãˆ": "ğŸ—¿ï¸"
            "Ã€": "âš°ï¸"
            "Ã‡": "ğŸ³ï¸â€ğŸŒˆï¸"
            "Ã™": "ğŸš½ï¸"
    chat:
        default:
            permissionNeeded: true
            permission: chat.default
        crypted:
            permissionNeeded: true
            permission: chat.crypted
        op:
            permissionNeeded: true
            permission: op
        owner:
            permissionNeeded: true
            permission: server.owner